name: project-cicd

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  test:
    name: CI Pipeline
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [18.15.0]

    steps:
      - uses: actions/checkout@v3
      - name: Create env file
        run: |
          touch .env
          cat <<EOF >> .env
          ${{ secrets.ENV }}
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Install Testing Packages
        run: npm install --save-dev jest node-mocks-http supertest

      - name: Run jest
        run: npx jest
